import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import styles from './layout.module.scss'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="X-UA-Compatible" content="room1" />
      </head>
      <body className={styles.room2Layout}>
        {children}
        <div className={styles.room2Header}>Copy right thanks jyjin @2000-2024</div>
      </body>
    </html>
  )
}
