"use client";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import styles from './layout.module.scss'
const inter = Inter({ subsets: ['latin'] })
import { useRouter } from 'next/navigation'
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter();

  const menu = [{
    id: 1,
    name: 'home1',
    path: '/home1'
  }, {
    id: 2,
    name: 'chat1',
    path: '/chat1'
  }, {
    id: 3,
    name: 'home2',
    path: '/home2'
  }, {
    id: 4,
    name: 'chat2',
    path: '/chat2'
  }]
  const renderMenu = () => {

    return <div className={styles.menu}>
      {menu.map((item, index) => {
        return <div className={styles.menuItem} key={item.id + item.name} onClick={()=>router.push(item.path)}>{item.name}</div>
      })}
    </div>

  }


  return (
    <html lang="en">
      <head>
        <meta httpEquiv="X-UA-Compatible" content="room" />
      </head>
      <body className={styles.room1Layout}>
        <div className={styles.room1Header}>NEXT APP 1</div>
        <div className={styles.main}>
          {renderMenu()}
          {children}
        </div>
      </body>
    </html>
  )
}
