import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
       <head>
        <meta http-equiv="X-UA-Compatible" content="room" />
      </head>
      <body className={inter.className}>
        <div style={{background: 'green'}}>room layout header</div>
        {children}</body>
    </html>
  )
}
