"use client";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import React, { useEffect } from 'react'
import styles from './layout.module.scss'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  useEffect(()=>{

  }, [])

  return (
    <html>
      <head>
        <meta httpEquiv="X-UA-Compatible" content="ie=edge" />
      </head>
      <body className={styles.appLayout}>
        <div className={styles.appHeader}>NEXT14 APP</div>
        {children}</body>
    </html>
  )
}
